trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  azure_static_web_apps_api_token: $(deployment_token)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Instalar Node.js'

  - script: |
      yarn install --frozen-lockfile
    displayName: 'Instalar dependencias'

  - script: |
      yarn build --configuration production && yarn copy-files
    displayName: 'Construir app Angular'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'dist/demo-acme-frutas-front/browser'
      output_location: ''
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
    displayName: 'Desplegar a Azure Static Web App'
